# Generated by Django 2.2.1 on 2019-06-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='line',
            field=models.CharField(default=None ,max_length=100),
        ),
    ]
