# Generated by Django 2.2.1 on 2019-06-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190606_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='line',
            field=models.CharField(max_length=100),
        ),
    ]
