# Generated by Django 2.2.1 on 2019-06-06 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managedb', '0006_auto_20190606_1054'),
        ('users', '0004_auto_20190606_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='dateofbirth',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='dateofstart',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='managedb.Sextype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='status_work',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='managedb.Statuswork'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='line',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
