# Generated by Django 2.2.2 on 2019-06-30 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managedb', '0006_auto_20190606_1054'),
        ('users', '0006_auto_20190630_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managedb.Statuswork'),
            preserve_default=False,
        ),
    ]
