# Generated by Django 2.2.1 on 2019-05-26 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Policytype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatusLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sta_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numofleave', models.IntegerField(default=0)),
                ('dep_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managedb.Department')),
                ('policy_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managedb.Policytype')),
                ('pos_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managedb.Position')),
            ],
            options={
                'unique_together': {('policy_name', 'dep_name', 'pos_name')},
            },
        ),
    ]
