# Generated by Django 2.2.1 on 2019-05-28 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managedb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policytype',
            name='policy_key',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='policytype',
            unique_together={('policy_key',)},
        ),
    ]
