# Generated by Django 2.2.1 on 2019-05-28 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managedb', '0002_auto_20190528_1037'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='policytype',
            unique_together=set(),
        ),
    ]
