# Generated by Django 2.2.1 on 2019-06-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedb', '0004_auto_20190528_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sextype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex_type', models.CharField(default='male', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Statuswork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_work', models.CharField(default='alive', max_length=20)),
            ],
        ),
    ]
