# Generated by Django 2.2.1 on 2019-06-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedb', '0005_sextype_statuswork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sextype',
            name='sex_type',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='statuswork',
            name='status_work',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
