# Generated by Django 2.2.1 on 2019-05-28 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managedbtrans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='explanation',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='history',
            name='user_hr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hr', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='user_sup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sup', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
