# Generated by Django 2.2.1 on 2019-05-28 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managedbtrans', '0002_auto_20190528_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managedb.Policytype'),
        ),
    ]
