# Generated by Django 2.2.1 on 2019-05-29 04:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('managedbtrans', '0003_auto_20190528_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='policy_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Remainleavedays'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
